class DDLHelper():

  def __init__(self, spark):
    self.spark = spark 

  def create_cost_lookup_table(self, target_catalog, target_schema):
    self.spark.sql(f"""
          create table if not exists {target_catalog}.{target_schema}.sku_cost_lookup 
          (
            sku string,
            list_price double
          )
    """                         
    )
  
  def insert_into_cost_lookup_table(self, target_catalog, target_schema):
    self.spark.sql(f"""insert overwrite {target_catalog}.{target_schema}.sku_cost_lookup
          values ('ENTERPRISE_ALL_PURPOSE_COMPUTE', 0.65),
          ('ENTERPRISE_ALL_PURPOSE_COMPUTE_DLT', 0.65),
          ('ENTERPRISE_ALL_PURPOSE_COMPUTE_PHOTON', 0.65),
          ('ENTERPRISE_DLT_ADVANCED_COMPUTE', 0.36),
          ('ENTERPRISE_DLT_ADVANCED_COMPUTE_PHOTON', 0.36),
          ('ENTERPRISE_DLT_CORE_COMPUTE', 0.2),
          ('ENTERPRISE_DLT_CORE_COMPUTE_PHOTON', 0.2),
          ('ENTERPRISE_DLT_PRO_COMPUTE', 0.25),
          ('ENTERPRISE_DLT_PRO_COMPUTE_PHOTON', 0.25),
          ('ENTERPRISE_JOBS_COMPUTE', 0.2),
          ('ENTERPRISE_JOBS_COMPUTE_PHOTON', 0.2),
          ('ENTERPRISE_JOBS_LIGHT_COMPUTE', 0.13),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_AP_SINGAPORE', 0.088),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_AP_SYDNEY', 0.088),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_CANADA', 0.078),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_EUROPE_FRANKFURT', 0.084),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_EUROPE_IRELAND', 0.078),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_LAUNCH_AP_SINGAPORE', 0.088),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_LAUNCH_AP_SYDNEY', 0.088),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_LAUNCH_CANADA', 0.078),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_LAUNCH_EUROPE_FRANKFURT', 0.084),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_LAUNCH_EUROPE_IRELAND', 0.078),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_LAUNCH_US_EAST_N_VIRGINIA', 0.07),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_LAUNCH_US_EAST_OHIO', 0.07),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_LAUNCH_US_WEST_OREGON', 0.07),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_US_EAST_N_VIRGINIA', 0.07),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_US_EAST_OHIO', 0.07),
          ('ENTERPRISE_SERVERLESS_REAL_TIME_INFERENCE_US_WEST_OREGON', 0.07),
          ('ENTERPRISE_SERVERLESS_SQL_COMPUTE', 0.55),
          ('ENTERPRISE_SERVERLESS_SQL_COMPUTE_AP_SYDNEY', 0.95),
          ('ENTERPRISE_SERVERLESS_SQL_COMPUTE_EUROPE_FRANKFURT', 0.91),
          ('ENTERPRISE_SERVERLESS_SQL_COMPUTE_EUROPE_IRELAND', 0.91),
          ('ENTERPRISE_SERVERLESS_SQL_COMPUTE_US_EAST_N_VIRGINIA', 0.7),
          ('ENTERPRISE_SERVERLESS_SQL_COMPUTE_US_EAST_OHIO', 0.7),
          ('ENTERPRISE_SERVERLESS_SQL_COMPUTE_US_WEST_OREGON', 0.7),
          ('ENTERPRISE_STORAGE_BACKUP_OPTIMIZED', 0.035),
          ('ENTERPRISE_STORAGE_BACKUP_OPTIMIZED_EUROPE_FRANKFURT', 0.035),
          ('ENTERPRISE_STORAGE_BACKUP_OPTIMIZED_EUROPE_IRELAND', 0.035),
          ('ENTERPRISE_STORAGE_BACKUP_OPTIMIZED_US_EAST_N_VIRGINIA', 0.035),
          ('ENTERPRISE_STORAGE_BACKUP_OPTIMIZED_US_EAST_OHIO', 0.035),
          ('ENTERPRISE_STORAGE_BACKUP_OPTIMIZED_US_WEST_OREGON', 0.035),
          ('ENTERPRISE_STORAGE_COLDLINE_ARCHIVE', 0.01),
          ('ENTERPRISE_STORAGE_COLDLINE_ARCHIVE_EUROPE_FRANKFURT', 0.01),
          ('ENTERPRISE_STORAGE_COLDLINE_ARCHIVE_EUROPE_IRELAND', 0.01),
          ('ENTERPRISE_STORAGE_COLDLINE_ARCHIVE_US_EAST_N_VIRGINIA', 0.01),
          ('ENTERPRISE_STORAGE_COLDLINE_ARCHIVE_US_EAST_OHIO', 0.01),
          ('ENTERPRISE_STORAGE_COLDLINE_ARCHIVE_US_WEST_OREGON', 0.01),
          ('ENTERPRISE_STORAGE_STANDARD', 0.02),
          ('ENTERPRISE_STORAGE_STANDARD_EUROPE_FRANKFURT', 0.02),
          ('ENTERPRISE_STORAGE_STANDARD_EUROPE_IRELAND', 0.02),
          ('ENTERPRISE_STORAGE_STANDARD_US_EAST_N_VIRGINIA', 0.02),
          ('ENTERPRISE_STORAGE_STANDARD_US_EAST_OHIO', 0.02),
          ('ENTERPRISE_STORAGE_STANDARD_US_WEST_OREGON', 0.02),
          ("STANDARD_ALL_PURPOSE_COMPUTE", 0.4),
          ("STANDARD_ALL_PURPOSE_COMPUTE_DLT", 0.4),
          ("STANDARD_ALL_PURPOSE_COMPUTE_PHOTON", 0.4),
          ("STANDARD_DLT_ADVANCED_COMPUTE", 0.36),
          ("STANDARD_DLT_ADVANCED_COMPUTE_PHOTON", 0.36),
          ("STANDARD_DLT_CORE_COMPUTE", 0.2),
          ("STANDARD_DLT_CORE_COMPUTE_PHOTON", 0.2),
          ("STANDARD_DLT_PRO_COMPUTE", 0.25),
          ("STANDARD_DLT_PRO_COMPUTE_PHOTON", 0.25),
          ("STANDARD_JOBS_COMPUTE", 0.1),
          ("STANDARD_JOBS_COMPUTE_PHOTON", 0.1),
          ("STANDARD_JOBS_LIGHT_COMPUTE", 0.07);
    """)